"""add documento_chunks table for RAG

Revision ID: b6e79b28a1ac
Revises: 7365b2b5446b
Create Date: 2026-10-01 19:12:37.407704

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector.sqlalchemy


# revision identifiers, used by Alembic.
revision: str = 'b6e79b28a1ac'
down_revision: Union[str, Sequence[str], None] = '7365b2b5446b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute('CREATE EXTENSION IF NOT EXISTS vector')
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('documento_chunks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('documento', sa.String(), nullable=True),
    sa.Column('titulo', sa.String(), nullable=True),
    sa.Column('seccion', sa.String(), nullable=True),
    sa.Column('texto', sa.String(), nullable=True),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('documento_chunks')
    # ### end Alembic commands ###
